const PREFIX = "CONSOLE.";

// ACTION TYPES
export const SET_CLEAR_CONSOLE_CALLBACK = PREFIX + "SET_CLEAR_CONSOLE_CALLBACK";
export const SET_PRINT_TO_CONSOLE_CALLBACK =
    PREFIX + "SET_PRINT_TO_CONSOLE_CALLBACK";
