defaults: &defaults #working_directory: ./circleci
    docker:
        - image: circleci/node:15.7.0
    working_directory: ~/repo

version: 2
jobs:
    prepare:
        <<: *defaults
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "yarn.lock" }}
            - run: yarn install --immutable
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "yarn.lock" }}
            - persist_to_workspace:
                  root: .
                  paths:
                      - node_modules
    build:
        <<: *defaults
        filters:
            branches:
                only:
                    - master
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run: yarn build
            - persist_to_workspace:
                  root: .
                  paths:
                      - build
    build_dev:
        <<: *defaults
        filters:
            branches:
                only:
                    - develop
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run: yarn build-dev
            - persist_to_workspace:
                  root: .
                  paths:
                      - build
    deploy:
        <<: *defaults
        environment:
          PRODUCTION: 1
        filters:
            branches:
                only:
                    - master
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run: >
                cp build/index.html functions &&
                cd functions &&
                yarn install &&
                npx firebase deploy -P default --only functions
            - run: yarn deploy
            - persist_to_workspace:
                  root: .
                  paths:
                      - build
    deploy_dev:
        <<: *defaults
        environment:
          PRODUCTION: 0
        filters:
            branches:
                only:
                    - develop
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run: >
                cp build/index.html functions &&
                cd functions &&
                yarn install &&
                npx firebase deploy -P develop --only functions
            - run: yarn deploy-dev
            - persist_to_workspace:
                  root: .
                  paths:
                      - build
workflows:
    version: 2
    build_accept_deploy:
        jobs:
            - prepare
            - build:
                  filters:
                      branches:
                          only:
                              - master
                  requires:
                      - prepare
            - build_dev:
                  filters:
                      branches:
                          only:
                              - develop
                  requires:
                      - prepare
            - deploy:
                  filters:
                      branches:
                          only:
                              - master
                  requires:
                      - build
            - deploy_dev:
                  filters:
                      branches:
                          only:
                              - develop
                  requires:
                      - build_dev
