export const SIGNIN_FAIL = "SIGNIN_FAIL";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const OPEN_DIALOG = "OPEN_DIALOG";
export const CLOSE_DIALOG = "CLOSE_DIALOG";
