name: "Deploy Develop"
on:
    push:
        branches:
            - develop
jobs:
    deploy-dev:
        name: deploy-develop
        runs-on: ubuntu-latest
        env:
            REACT_APP_DATABASE: DEV
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: yarn
            - name: Build
              run: |
                  yarn install
                  echo "STORAGE_BUCKET_URL=gs://csound-ide-dev.appspot.com" >> functions/.env.dev
                  PUBLIC_URL="https://csound-ide-dev.web.app" yarn build:dev
                  cp dist/index.html functions
                  cd functions
                  yarn install
                  yarn build
            - name: Deploy to Firebase
              uses: w9jds/firebase-action@master
              with:
                  args: deploy -P develop
              env:
                  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_DEV }}
