name: "Deploy Production"
on:
    push:
        branches:
            - master
jobs:
    deploy-prod:
        name: deploy-production
        runs-on: ubuntu-latest
        env:
            REACT_APP_DATABASE: PROD
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Build
              run: |
                  yarn install
                  echo "STORAGE_BUCKET_URL=gs://csound-ide.appspot.com" >> functions/.env
                  PUBLIC_URL="https://ide.csound.com" PRODUCTION=1 yarn build
                  cp dist/index.html functions
                  cd functions
                  yarn install
                  yarn build
            - name: Deploy to Firebase
              uses: w9jds/firebase-action@master
              with:
                  args: deploy -P default
              env:
                  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_PROD }}
                  REACT_APP_DATABASE: PROD
