name: "Deploy Production"
on:
    push:
        branches:
            - master
jobs:
    deploy-prod:
        name: deploy-production
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Build
              run: |
                  yarn install
                  PUBLIC_URL="https://ide.csound.com" PRODUCTION=1 yarn build
                  cp build/index.html functions
                  cd functions
                  yarn install
            - name: Deploy to Firebase
              uses: w9jds/firebase-action@master
              with:
                  args: deploy -P default
              env:
                  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_PROD }}
                  REACT_APP_DATABASE: PROD
